hyp:
  batch_size: 64
  epochs: 100
  lr: 0.0001
  beta1: 0.1
  beta2: 0.99
  timesteps: 1000
data:
  num_workers: 4
  img_size: 64
  img_ch: 3
log:
  device: "cuda:0"
  log_num: 2
  load_epoch: 0
  save_freq: 1
  save_dir: "logs/"
  name: "ddpm"