hyp:
  hid_dim: 3
  batch_size: 16
  epochs: 100
  lr: 0.0001
  beta1: 0.9
  beta2: 0.99
  timesteps: 1000
  init_dim: 64

data:
  num_workers: 4
  img_size: 64
  img_ch: 3
exp:
  device: "cuda:0"
  try_num: 1
  load_epoch: 0
  save_freq: 1
  save_dir: "logs/"
  name: "ddpm"