vqgan:
  model:
    in_channels: 3
    hid_channels: 64
    channels_mult: [1,2,4,8]
    num_res_layers: 2
    attn_resolutions: []
    resolution: 64
    num_embed: 1024
    embed_dim: 3
    beta: 0.25
train:
  lr: 0.0001
  epochs: 100
  batch_size: 48
  beta1: 0.5
  beta2: 0.99
  disc_factor: 1.
data:
  num_workers: 4
  img_size: 64
  img_ch: 3
log:
  device: "cuda:0"
  log_num: 6
  load_epoch: 0
  save_freq: 5
  save_dir: "logs/"
  name: "vqgan-nodisc"