hyp:
  batch_size: 64
  epochs: 100
  lr: 0.0001
  beta1: 0.1
  beta2: 0.99
  timesteps: 1000

  # VQ-VAE specific hyperparameters
  in_dim: 3
  h_dim: 128
  res_h_dim: 32
  n_res_layers: 2
  num_embeddings: 512 # K
  embedding_dim: 64   # D
  beta: 0.25
data:
  num_workers: 4
  img_size: 64
  img_ch: 3
log:
  device: "cuda:0"
  log_num: 1
  load_epoch: 0
  save_freq: 20
  save_dir: "logs/"
  name: "vqvae"